render_config() (
  umask 077
  local destination=$1 rendered
  rendered=$(mktemp) || return 1
  trap 'rm -f -- "$rendered"' EXIT
  jq -n \
    --argjson port "$PORT" \
    --arg id "$UUID" \
    --arg extraIds "${EXTRA_UUIDS:-}" \
    --arg server "$SERVER_NAME" \
    --arg private "${PRIVATE_KEY:-}" \
    --arg short "${SHORT_ID:-}" \
    --arg profile "${PROFILE:-vless-reality-raw}" \
    --arg path "${PATH_VALUE:-}" \
    --arg listen "$(if [[ ${PROFILE:-} == vless-tls-xhttp ]]; then printf '127.0.0.1'; elif [[ ${ADDRESS:-} == *:* ]]; then printf '::'; else printf '0.0.0.0'; fi)" \
    --arg cert "${TLS_CERT_PATH_OVERRIDE:-$(tls_cert_path)}" \
    --arg key "${TLS_KEY_PATH_OVERRIDE:-$(tls_key_path)}" '{
      log: {loglevel: "warning"},
      inbounds: [{
        tag: "vless-reality",
        listen: $listen,
        port: $port,
        protocol: (if $profile == "hysteria-tls-quic" then "hysteria" elif ($profile | startswith("trojan-")) then "trojan" elif ($profile | startswith("vmess-")) then "vmess" else "vless" end),
        settings: (if $profile == "hysteria-tls-quic" then {version:2,clients: (([$id] + ($extraIds | split(",") | map(select(length > 0)))) | map({auth: .}))}
        elif ($profile | startswith("trojan-")) then {clients: (([$id] + ($extraIds | split(",") | map(select(length > 0)))) | map({password: .}))}
        elif ($profile | startswith("vmess-")) then {clients: (([$id] + ($extraIds | split(",") | map(select(length > 0)))) | map({id: ., alterId: 0}))}
        else {
          clients: (([$id] + ($extraIds | split(",") | map(select(length > 0)))) | map({id: .} + (if ($profile == "vless-reality-raw" or $profile == "vless-tls-raw") then {flow: "xtls-rprx-vision"} else {} end))),
          decryption: "none"
        } end),
        streamSettings: ({
          network: (if $profile == "hysteria-tls-quic" then "hysteria" elif ($profile == "vless-reality-xhttp" or $profile == "vless-tls-xhttp") then "xhttp" elif ($profile | endswith("-grpc")) then "grpc" elif ($profile | endswith("-ws")) then "ws" else "raw" end),
          security: (if $profile == "vless-tls-xhttp" then "none" elif ($profile | contains("-tls-")) then "tls" elif ($profile | contains("-reality-")) then "reality" else "none" end)
        } + (if ($profile | contains("-reality-")) then {realitySettings: {
            show: false,
            target: ($server + ":443"),
            xver: 0,
            serverNames: [$server],
            privateKey: $private,
            shortIds: [$short]
          }} elif ($profile | contains("-tls-") and $profile != "vless-tls-xhttp") then {tlsSettings: ({certificates: [{certificateFile: $cert, keyFile: $key}]} + (if $profile == "hysteria-tls-quic" then {alpn:["h3"]} else {} end))} else {} end)
          + (if $profile == "hysteria-tls-quic" then {hysteriaSettings:{version:2}}
            elif ($profile == "vless-reality-xhttp" or $profile == "vless-tls-xhttp") then {xhttpSettings: {path: $path, mode: "auto"}}
            elif ($profile | endswith("-grpc")) then {grpcSettings: {serviceName: $path, multiMode: false}}
            elif ($profile | endswith("-ws")) then {wsSettings: {path: $path}}
            else {} end)),
        sniffing: {enabled: true, destOverride: ["http", "tls", "quic"]}
      }],
      outbounds: [
        {protocol: "freedom", tag: "direct"},
        {protocol: "blackhole", tag: "block"}
      ]
    }' > "$rendered" || return 1
  protect_outbound_targets "$rendered" || return 1
  cat "$rendered" > "$destination"
)

apply_warp_config() {
  local config_file=$1 mode domains strategy
  protect_outbound_targets "$config_file" || return 1
  [[ -r $WARP_STATE_FILE ]] || return 0
  WARP_MODE=off
  WARP_DOMAINS=''
  WARP_IP_STRATEGY=UseIPv4v6
  # This file is generated by this script with mode 0600.
  # shellcheck disable=SC1090
  load_state_file "$WARP_STATE_FILE"
  mode=${WARP_MODE:-off}
  domains=${WARP_DOMAINS:-}
  strategy=${WARP_IP_STRATEGY:-UseIPv4v6}
  [[ $mode == off ]] && return 0
  [[ $mode == selective || $mode == all ]] || { red "WARP 策略模式无效。" >&2; return 1; }
  [[ $strategy == UseIPv4v6 || $strategy == UseIPv4 || $strategy == UseIPv6 ]] || { red "WARP IP 策略无效。" >&2; return 1; }
  if [[ $mode == selective && -z $domains ]]; then
    red "WARP 指定域名列表为空。" >&2
    return 1
  fi
  inject_warp_config "$config_file" "$mode" "$domains" "$strategy"
}

inject_warp_config() {
  local config_file=$1 mode=$2 domains=${3:-} strategy=${4:-UseIPv4v6} temporary
  protect_outbound_targets "$config_file" || return 1
  temporary=$(mktemp)
  jq --arg mode "$mode" --arg domains "$domains" --arg strategy "$strategy" --argjson port "$WARP_PROXY_PORT" '
    .outbounds += [{protocol:"socks",tag:"warp",targetStrategy:$strategy,settings:{servers:[{address:"127.0.0.1",port:$port}]}}]
    | .routing = {
        domainStrategy:"IPOnDemand",
        rules: (.routing.rules
          + if $mode == "all" then
              [{type:"field",network:"tcp",outboundTag:"warp"}]
            else
              [{type:"field",network:"tcp",domain:($domains | split(",")),outboundTag:"warp"}]
            end)
      }
  ' "$config_file" > "$temporary" || { rm -f -- "$temporary"; return 1; }
  mv -f -- "$temporary" "$config_file"
}

write_config() {
  local node_file=${1:-$NODES_DIR/primary.env}
  ensure_service_user
  install -d -m 755 "$CONFIG_DIR"
  create_backup
  prepare_tls_material
  validate_pending_config node
  [[ -f $STATE_FILE ]] || save_current_node "$STATE_FILE"
  install -d -m 700 "$NODES_DIR"
  save_current_node "$node_file"
  rebuild_or_restore
}

# Keep credentials private from creation, including on failure or interruption.
# Xray determines the configuration format from the final file extension.
validate_pending_config() (
  umask 077
  local mode=$1 temporary_dir temporary
  temporary_dir=$(mktemp -d "$CONFIG_DIR/.config.XXXXXX") || return 1
  trap 'rm -rf -- "$temporary_dir"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  temporary="$temporary_dir/config.json"
  if [[ $mode == empty ]]; then
    jq -n '{log:{loglevel:"warning"},inbounds:[],outbounds:[{protocol:"freedom",tag:"direct"},{protocol:"blackhole",tag:"block"}]}' > "$temporary" || return 1
  else
    render_config "$temporary" || return 1
  fi
  apply_warp_config "$temporary" || return 1
  XRAY_LOCATION_ASSET="$ASSET_DIR" "$XRAY_BIN" run -test -config "$temporary" || return 1
  if [[ $mode == empty ]]; then
    publish_config "$temporary" || return 1
  fi
)

write_empty_config() {
  ensure_service_user
  install -d -m 755 "$CONFIG_DIR"
  install -d -m 700 "$NODES_DIR"
  validate_pending_config empty
  write_data_schema_marker "$STATE_FILE"
}

valid_state_key() {
  case "$1" in
    DATA_SCHEMA|PORT|UUID|EXTRA_UUIDS|ADDRESS|PROFILE|PATH_VALUE|CERT_SOURCE|KEY_SOURCE|SERVER_NAME|PRIVATE_KEY|PUBLIC_KEY|SHORT_ID|REMARK|XHTTP_MODE|WARP_MODE|WARP_DOMAINS|WARP_IP_STRATEGY|WARP_BACKEND) return 0 ;;
    *) return 1 ;;
  esac
}

# Decode the literal formats emitted by Bash printf %q, never eval/source them.
decode_legacy_value() {
  local encoded=$1 char index
  DECODED_STATE_VALUE=''
  if [[ $encoded == \$\'*\' ]]; then
    DECODED_STATE_VALUE=$(printf '%b.' "${encoded:2:${#encoded}-3}")
    DECODED_STATE_VALUE=${DECODED_STATE_VALUE%.}
  elif [[ $encoded == \"*\" || $encoded == \'*\' ]]; then
    DECODED_STATE_VALUE=${encoded:1:${#encoded}-2}
  else
    for ((index=0; index<${#encoded}; index++)); do
      char=${encoded:index:1}
      if [[ $char == $'\\' ]]; then
        ((index+=1)); (( index < ${#encoded} )) || return 1
        char=${encoded:index:1}
      elif [[ $char == [[:space:]] || $char == [\$\`\'\"\;\&\|\<\>\(\)\{\}] ]]; then
        return 1
      fi
      DECODED_STATE_VALUE+=$char
    done
  fi
}

state_to_json() {
  local file=$1 first line key encoded
  [[ -f $file ]] || return 1
  first=$(head -c 1 "$file") || return 1
  if [[ $first == '{' ]]; then
    jq -e 'type == "object"' "$file" >/dev/null || return 1
    cat "$file"
  else
    (
      while IFS= read -r line || [[ -n $line ]]; do
        line=${line%$'\r'}
        [[ -n $line && $line != \#* ]] || continue
        [[ $line == *=* ]] || return 1
        key=${line%%=*}; encoded=${line#*=}
        valid_state_key "$key" || return 1
        decode_legacy_value "$encoded" || return 1
        printf '%s\0%s\0' "$key" "$DECODED_STATE_VALUE"
      done < "$file"
    ) | jq -Rs 'split("\u0000")[:-1] | . as $p | [range(0; length; 2) | {key:$p[.],value:$p[.+1]}] | from_entries |
      if has("DATA_SCHEMA") then .DATA_SCHEMA |= tonumber else . end |
      if has("PORT") then .PORT |= tonumber else . end'
  fi
}

load_state_file() {
  local file=$1 temporary key value invalid=0
  temporary=$(mktemp) || return 1
  if ! state_to_json "$file" | jq -ej '
      if (type == "object" and all(.[]; type == "string" or type == "number") and all(.[] | tostring; contains("\u0000") | not))
      then to_entries[] | .key, "\u0000", (.value|tostring), "\u0000" else error("invalid state") end' > "$temporary"; then
    rm -f -- "$temporary"; red '状态文件格式无效，未执行其内容。' >&2; return 1
  fi
  # Validate every key before assigning any field.
  while IFS= read -r -d '' key && IFS= read -r -d '' value; do
    valid_state_key "$key" || invalid=1
  done < "$temporary"
  if (( invalid )); then rm -f -- "$temporary"; return 1; fi
  EXTRA_UUIDS=''; XHTTP_MODE=auto
  while IFS= read -r -d '' key && IFS= read -r -d '' value; do
    printf -v "$key" '%s' "$value"
  done < "$temporary"
  rm -f -- "$temporary"
}

state_schema() { state_to_json "$1" | jq -r '.DATA_SCHEMA // 1'; }

save_current_node() (
  umask 077
  local destination=$1 temporary json_file
  temporary=$(mktemp "${destination}.XXXXXX") || return 1
  json_file=$(mktemp "${destination}.XXXXXX") || return 1
  trap 'rm -f -- "$temporary" "$json_file"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  cat > "$temporary" <<EOF || return 1
DATA_SCHEMA=${DATA_SCHEMA_VERSION}
PORT=${PORT}
UUID=${UUID}
EXTRA_UUIDS=$(printf %q "${EXTRA_UUIDS:-}")
ADDRESS=$(printf %q "${ADDRESS:-}")
PROFILE=$(printf %q "${PROFILE:-vless-reality-raw}")
PATH_VALUE=$(printf %q "${PATH_VALUE:-}")
CERT_SOURCE=$(printf %q "${CERT_SOURCE:-}")
KEY_SOURCE=$(printf %q "${KEY_SOURCE:-}")
SERVER_NAME=$(printf %q "$SERVER_NAME")
PRIVATE_KEY=$(printf %q "${PRIVATE_KEY:-}")
PUBLIC_KEY=$(printf %q "${PUBLIC_KEY:-}")
SHORT_ID=$(printf %q "${SHORT_ID:-}")
REMARK=$(printf %q "$REMARK")
XHTTP_MODE=$(printf %q "${XHTTP_MODE:-auto}")
EOF
  state_to_json "$temporary" > "$json_file" || return 1
  mv -f -- "$json_file" "$destination"
)

rebuild_config_from_nodes() (
  install -d -m 700 "$NODES_DIR" || return 1
  local work_dir combined node_file node_id rendered
  work_dir=$(mktemp -d) || return 1
  trap 'rm -rf -- "$work_dir"' EXIT
  combined="$work_dir/inbounds.json"
  printf '[]\n' > "$combined" || return 1
  for node_file in "$NODES_DIR"/*.env; do
    [[ -e $node_file ]] || continue
    # Node files are generated by this script with mode 0600.
    # shellcheck disable=SC1090
    EXTRA_UUIDS=''
    # shellcheck disable=SC1090
    load_state_file "$node_file" || return 1
    node_id=$(basename "$node_file" .env)
    rendered="$work_dir/${node_id}.json"
    render_config "$rendered" || return 1
    jq --arg tag "$node_id" '.inbounds[0].tag=$tag | .inbounds[0]' "$rendered" > "$work_dir/inbound.json" || return 1
    jq --slurpfile inbound "$work_dir/inbound.json" '. + $inbound' "$combined" > "$work_dir/next.json" || return 1
    mv "$work_dir/next.json" "$combined" || return 1
  done
  jq -n --slurpfile inbounds "$combined" '{log:{loglevel:"warning"},inbounds:$inbounds[0],outbounds:[{protocol:"freedom",tag:"direct"},{protocol:"blackhole",tag:"block"}]}' > "$work_dir/config.json" || return 1
  apply_warp_config "$work_dir/config.json" || return 1
  XRAY_LOCATION_ASSET="$ASSET_DIR" "$XRAY_BIN" run -test -config "$work_dir/config.json" >/dev/null || { rm -rf "$work_dir"; red "多入站配置未通过 Xray 校验。"; return 1; }
  publish_config "$work_dir/config.json"
)

rebuild_or_restore() {
  rebuild_config_from_nodes && return 0
  if [[ -n ${LAST_BACKUP:-} ]]; then
    yellow "合并配置失败，正在恢复入站注册表和配置…"
    restore_archive "$LAST_BACKUP"
  fi
  die "多入站配置生成失败，已回滚。"
}

write_service() {
  cat > "$SERVICE_FILE" <<'EOF'
[Unit]
Description=Xray Service managed by v2ray-manager
Documentation=https://xtls.github.io/
After=network-online.target nss-lookup.target
Wants=network-online.target

[Service]
User=xray
Environment=XRAY_LOCATION_ASSET=/usr/local/share/xray
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictSUIDSGID=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
ExecStart=/usr/local/bin/xray-core run -config /etc/xray/config.json
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
}

install_manager_command() {
  [[ -r "$0" ]] || die "无法读取当前脚本，未能安装 v2ray 管理命令。"
  if [[ -L "$MANAGER_BIN" && ! -e "$MANAGER_BIN" ]]; then
    yellow "检测到失效的 v2ray 命令链接，正在修复。"
    rm -f -- "$MANAGER_BIN"
  fi
  if [[ "$(readlink -f "$0")" != "$(readlink -f "$MANAGER_BIN" 2>/dev/null || true)" ]]; then
    if [[ -e "$MANAGER_BIN" ]] && ! grep -q 'APP_NAME="v2ray-manager"' "$MANAGER_BIN" 2>/dev/null; then
      install -d -m 700 "$BACKUP_DIR"
      if [[ ! -e "$LEGACY_MANAGER_BACKUP" ]]; then
        cp -a "$MANAGER_BIN" "$LEGACY_MANAGER_BACKUP"
        yellow "已保存现有 v2ray 管理命令：$LEGACY_MANAGER_BACKUP"
      fi
    fi
    install -m 755 "$0" "$MANAGER_BIN"
  fi
}

stop_legacy_service() {
  if [[ -f /etc/v2ray/manager.env && -f /etc/systemd/system/v2ray.service ]] && \
     grep -q '/usr/local/bin/v2ray-core' /etc/systemd/system/v2ray.service; then
    yellow "检测到本项目 1.x 服务，正在停用；旧文件会保留以便人工回退。"
    systemctl disable --now v2ray 2>/dev/null || true
  fi
}
