migrate_project_state() (
  local before after node_file credential domain upstream path has_tls_xhttp=0 was_active=0
  local migration_dir
  migration_dir=$(mktemp -d) || return 1
  trap 'rm -rf -- "$migration_dir"' EXIT
  local -a extra_credentials
  check_state_schema || return 1
  [[ -d $NODES_DIR ]] || { green "项目脚本已更新；当前没有需要迁移的入站状态。"; return 0; }
  if ! compgen -G "$NODES_DIR/*.env" >/dev/null && ! compgen -G "$NODES_DIR/*.disabled" >/dev/null; then
    green "项目脚本已更新；当前没有需要迁移的入站。"
    return 0
  fi
  [[ -r $CONFIG_FILE && -x $XRAY_BIN ]] || die "更新后迁移需要现有 Xray 配置和内核。"
  systemctl is-active --quiet "$SERVICE_NAME" && was_active=1
  cp "$CONFIG_FILE" "$migration_dir/before.json" || return 1
  before=$(migration_connection_fingerprint "$CONFIG_FILE")
  create_backup
  [[ -n ${LAST_BACKUP:-} ]] || die "无法创建更新前配置备份，已停止迁移。"

  for node_file in "$NODES_DIR"/*.env "$NODES_DIR"/*.disabled; do
    [[ -e $node_file ]] || continue
    DATA_SCHEMA=1
    EXTRA_UUIDS=''
    # Node files are generated by this script with mode 0600.
    # shellcheck disable=SC1090
    load_state_file "$node_file" || { restore_archive "$LAST_BACKUP"; die "无法读取入站状态，已恢复更新前配置。"; }
    [[ ${DATA_SCHEMA:-1} =~ ^[0-9]+$ ]] || {
      restore_archive "$LAST_BACKUP"
      die "入站数据版本无效，已恢复更新前配置。"
    }
    if ! valid_profile "$PROFILE" || ! valid_port "$PORT" || ! valid_uuid "$UUID"; then
      restore_archive "$LAST_BACKUP"
      die "入站状态未通过迁移校验，已恢复更新前配置。"
    fi
    [[ $PROFILE != vless-tls-xhttp ]] || has_tls_xhttp=1
    if [[ -n ${EXTRA_UUIDS:-} ]]; then
      IFS=',' read -r -a extra_credentials <<<"$EXTRA_UUIDS"
      (( ${#extra_credentials[@]} <= 9 )) || {
        restore_archive "$LAST_BACKUP"; die "入站链接数量超过上限，已恢复更新前配置。"
      }
      for credential in "${extra_credentials[@]}"; do
        valid_uuid "$credential" || {
          restore_archive "$LAST_BACKUP"; die "子链接凭据未通过迁移校验，已恢复更新前配置。"
        }
      done
    fi
    save_current_node "$node_file"
  done
  write_data_schema_marker "$STATE_FILE" || {
    restore_archive "$LAST_BACKUP"; die "状态版本写入失败，已恢复更新前配置。"
  }
  rebuild_config_from_nodes || {
    restore_archive "$LAST_BACKUP"; die "更新后配置重建失败，已恢复更新前配置。"
  }
  after=$(migration_connection_fingerprint "$CONFIG_FILE")
  if [[ $before != "$after" ]]; then
    restore_archive "$LAST_BACKUP"
    die "迁移导致连接参数发生非预期变化，已恢复原配置和原链接。"
  fi
  if (( was_active )); then
    restart_checked || {
      restore_archive "$LAST_BACKUP"
      restart_checked || true
      die "迁移后 Xray 启动失败，已恢复旧配置。"
    }
  fi
  if (( has_tls_xhttp )); then
    while IFS= read -r domain; do
      [[ -n $domain ]] || continue
      if command -v caddy >/dev/null 2>&1 && [[ -f $CADDY_SITE_DIR/$domain.caddy ]]; then
        IFS=$'\t' read -r upstream path < <(find_caddy_xray_defaults "$domain")
        if ! configure_caddy_site xray "$domain" "$upstream" "$path"; then
          die "迁移失败：$domain 的 Caddy 路由同步失败，正在恢复升级前配置。"
        fi
      else
        if jq -e 'any(.inbounds[]; .protocol == "vless" and .streamSettings.network == "xhttp" and .streamSettings.security == "tls")' "$migration_dir/before.json" >/dev/null; then
          die "迁移失败：$domain 缺少 Caddy 入口，不能移除现有 TLS 监听。"
        fi
        yellow "$domain 尚未配置 Caddy 入口；本次不改变其客户端参数。"
      fi
    done < <(for node_file in "$NODES_DIR"/*.env; do
      [[ -f $node_file ]] || continue
      PROFILE=''; SERVER_NAME=''
      # shellcheck disable=SC1090
      load_state_file "$node_file"
      [[ $PROFILE == vless-tls-xhttp ]] && printf '%s\n' "$SERVER_NAME"
    done | sort -u)
  fi
  rm -rf -- "$migration_dir"
  green "项目数据已迁移到版本 $DATA_SCHEMA_VERSION；已核验各入站连接参数。"
)

check_state_schema() {
  local state schema supported=${1:-$DATA_SCHEMA_VERSION}
  [[ $supported =~ ^[1-9][0-9]{0,5}$ ]] || { red '候选脚本未声明有效的数据结构版本。' >&2; return 1; }
  for state in "$STATE_FILE" "$NODES_DIR"/*.env "$NODES_DIR"/*.disabled; do
    [[ -f $state ]] || continue
    schema=$(state_schema "$state") || return 1
    schema=${schema:-1}
    [[ $schema =~ ^[1-9][0-9]{0,5}$ ]] || { red "数据版本无效：$state" >&2; return 1; }
    (( schema <= supported )) || { red "数据版本 $schema 高于目标脚本支持的 $supported，拒绝降级迁移。" >&2; return 1; }
  done
}

ensure_project_state_current() {
  local command_name=${1:-menu} node_file schema needs_migration=0
  [[ $command_name != migrate && $command_name != uninstall ]] || return 0
  check_state_schema || return 1
  for node_file in "$NODES_DIR"/*.env "$NODES_DIR"/*.disabled; do
    [[ -f $node_file ]] || continue
    schema=$(state_schema "$node_file")
    [[ ${schema:-1} == "$DATA_SCHEMA_VERSION" ]] || needs_migration=1
  done
  (( needs_migration )) || return 0
  yellow "检测到旧版项目数据，正在自动迁移并保护现有链接…"
  run_mutation migrate_project_state
}

manager_bundle_path() {
  case "$1" in
    manager) printf '%s\n' "$MANAGER_BIN" ;;
    config) printf '%s\n' "$CONFIG_DIR" ;;
    caddy-main) printf '%s\n' "$CADDY_CONFIG" ;;
    caddy-sites) printf '%s\n' "$CADDY_SITE_DIR" ;;
    service) printf '%s\n' "$SERVICE_FILE" ;;
    components) printf '%s\n' "$WARP_BACKEND_BIN_DIR" ;;
    hysteria-bin) printf '%s\n' "$HYSTERIA_BIN" ;;
    hysteria-config) printf '%s\n' "$HYSTERIA_CONFIG_DIR" ;;
    hysteria-service) printf '%s\n' "$HYSTERIA_SERVICE_TEMPLATE" ;;
    *) return 1 ;;
  esac
}

capture_manager_bundle() (
  set -Eeuo pipefail
  umask 077
  local bundle=$1 name path links xray_active=false caddy_active=false
  mkdir "$bundle/files" || return 1
  for name in manager config caddy-main caddy-sites service components hysteria-bin hysteria-config hysteria-service; do
    path=$(manager_bundle_path "$name") || return 1
    if [[ -e $path || -L $path ]]; then
      # cp -a would preserve references to mutable external files rather than
      # their state. Refuse that layout before journaling or replacing anything.
      links=$(find "$path" -type l -print -quit) || return 1
      [[ -z $links ]] || { red "关联快照暂不支持符号链接：$links；未修改现有安装。" >&2; return 1; }
      cp -a -- "$path" "$bundle/files/$name" || return 1
    fi
  done
  [[ -f $bundle/files/manager ]] || return 1
  systemctl is-active --quiet "$SERVICE_NAME" && xray_active=true
  systemctl is-active --quiet caddy && caddy_active=true
  jq -n --arg version "$MANAGER_VERSION" --argjson schema "$DATA_SCHEMA_VERSION" \
    --argjson xray "$xray_active" --argjson caddy "$caddy_active" \
    '{format:1,manager_version:$version,data_schema:$schema,xray_active:$xray,caddy_active:$caddy}' > "$bundle/metadata.json" || return 1
  # A saved coordinator remains usable even if the installed manager is older
  # and does not yet implement the recover command.
  cp -- "${BASH_SOURCE[0]}" "$bundle/recovery.sh" || return 1
  (cd "$bundle" && find files -type f -exec sha256sum {} + > checksums && sha256sum metadata.json recovery.sh >> checksums) || return 1
)

read_manager_pointer() {
  local id
  [[ -f $1 ]] || return 1
  IFS= read -r id < "$1" || return 1
  [[ $id =~ ^manager-transaction\.[A-Za-z0-9]+$ ]] || return 1
  [[ -d $BACKUP_DIR/$id && ! -L $BACKUP_DIR/$id ]] || return 1
  printf '%s\n' "$BACKUP_DIR/$id"
}

publish_manager_pointer() (
  local destination=$1 bundle=$2 temporary
  temporary=$(mktemp "$BACKUP_DIR/pointer.XXXXXX") || return 1
  trap 'rm -f -- "$temporary"' EXIT
  printf '%s\n' "${bundle##*/}" > "$temporary" || return 1
  atomic_install "$temporary" "$destination" 600
)

require_no_pending_manager() {
  [[ ! -e $BACKUP_DIR/manager.pending ]] || {
    red "存在未完成的管理脚本事务。先运行 v2ray recover；恢复入口位于 $BACKUP_DIR/manager-transaction.*/recovery.sh。" >&2
    return 1
  }
}

restore_manager_bundle() {
  local bundle=$1 name path xray_active caddy_active
  [[ -f $bundle/checksums && -f $bundle/metadata.json && -f $bundle/files/manager ]] || return 1
  (cd "$bundle" && sha256sum -c checksums >/dev/null) || return 1
  jq -e '.format == 1 and (.xray_active | type == "boolean") and (.caddy_active | type == "boolean")' "$bundle/metadata.json" >/dev/null || return 1
  validate_manager "$bundle/files/manager" || return 1
  xray_active=$(jq -r '.xray_active' "$bundle/metadata.json") || return 1
  caddy_active=$(jq -r '.caddy_active' "$bundle/metadata.json") || return 1
  # Restore directories exactly, including removal of post-upgrade nodes.
  # Manager replacement is last; the saved recovery entry survives partial I/O.
  systemctl stop 'hysteria-v2ray-manager@*.service' >/dev/null 2>&1 || true
  for name in config caddy-main caddy-sites service components hysteria-bin hysteria-config hysteria-service; do
    path=$(manager_bundle_path "$name") || return 1
    rm -rf -- "$path" || return 1
    if [[ -e $bundle/files/$name ]]; then
      mkdir -p -- "$(dirname "$path")" || return 1
      cp -a -- "$bundle/files/$name" "$path" || return 1
    fi
  done
  atomic_install "$bundle/files/manager" "$MANAGER_BIN" 755 || return 1
  systemctl daemon-reload || return 1
  if [[ -f $CONFIG_FILE ]]; then
    XRAY_LOCATION_ASSET="$ASSET_DIR" "$XRAY_BIN" run -test -config "$CONFIG_FILE" >/dev/null || return 1
  fi
  if [[ $xray_active == true ]]; then
    systemctl restart "$SERVICE_NAME" && service_healthy || return 1
  elif systemctl is-active --quiet "$SERVICE_NAME"; then systemctl stop "$SERVICE_NAME" || return 1; fi
  if [[ $xray_active == true && -d $bundle/files/hysteria-config ]]; then
    sync_hysteria_services || return 1
  fi
  if [[ $caddy_active == true ]]; then
    caddy validate --config "$CADDY_CONFIG" >/dev/null || return 1
    systemctl restart caddy || return 1
    systemctl is-active --quiet caddy || return 1
  elif systemctl is-active --quiet caddy; then systemctl stop caddy || return 1; fi
}

finish_manager_transaction() {
  local status=$1 bundle=$2 armed=$3 committed=$4
  trap - EXIT INT TERM
  if (( armed && ! committed )); then
    if restore_manager_bundle "$bundle"; then
      rm -f -- "$BACKUP_DIR/manager.pending" || exit 1
      yellow '操作失败，已恢复关联的管理脚本、数据、组件脚本和服务状态。' >&2
    else
      red "自动恢复未完成；保留现场。运行：bash $bundle/recovery.sh recover" >&2
    fi
    exit 1
  fi
  exit "$status"
}

recover_manager() {
  local bundle
  bundle=$(read_manager_pointer "$BACKUP_DIR/manager.pending") || die '没有有效的待恢复事务。'
  restore_manager_bundle "$bundle" || die "恢复未完成，快照保留在 $bundle。"
  rm -f -- "$BACKUP_DIR/manager.pending" || return 1
  green '已恢复中断操作之前的管理脚本与关联数据。'
}

update_manager() (
  set -Eeuo pipefail
  local temporary revision url candidate_schema bundle='' armed=0 committed=0
  temporary=$(mktemp)
  trap 'status=$?; rm -f -- "$temporary"; finish_manager_transaction "$status" "$bundle" "$armed" "$committed"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  require_no_pending_manager
  revision=${V2M_MANAGER_REF:-}
  if [[ -z $revision ]]; then
    revision=$(curl --fail --silent --show-error --location --retry 3 --connect-timeout 15 \
      --max-time 60 "$MANAGER_API" | jq -r '.sha') || {
      red '无法取得 GitHub 提交，管理脚本尚未替换。若 curl 报 Could not resolve host，请先检查 DNS 和 IP 出站；此错误不能单独证明 WARP 故障。' >&2
      return 1
    }
  fi
  [[ $revision =~ ^[0-9a-f]{40}$ ]] || die "管理脚本版本必须是完整的 Git 提交 SHA。"
  url="${MANAGER_URL%/main/v2ray.sh}/$revision/v2ray.sh"
  green "下载管理脚本提交：$revision"
  download_file "$url" "$temporary"
  validate_manager "$temporary" || die "下载的管理脚本未通过语法或项目标识检查，未更新。"
  candidate_schema=$(awk -F '"' '/^readonly DATA_SCHEMA_VERSION="/{print $2; exit}' "$temporary")
  [[ -n $candidate_schema ]] || die '候选脚本缺少数据结构版本，拒绝覆盖现有安装。'
  check_state_schema "$candidate_schema"
  [[ -f $MANAGER_BIN ]] || die "找不到当前管理脚本。"
  install -d -m 700 "$BACKUP_DIR"
  bundle=$(mktemp -d "$BACKUP_DIR/manager-transaction.XXXXXX")
  capture_manager_bundle "$bundle"
  publish_manager_pointer "$BACKUP_DIR/manager.pending" "$bundle"
  armed=1
  # Kept for manual inspection only. Automated rollback requires the bundle.
  atomic_install "$MANAGER_BIN" "$BACKUP_DIR/manager.previous.sh" 700
  atomic_install "$temporary" "$MANAGER_BIN" 755
  V2M_INTERNAL_MIGRATION=1 "$MANAGER_BIN" migrate
  publish_manager_pointer "$BACKUP_DIR/manager.rollback" "$bundle"
  committed=1
  rm -f -- "$BACKUP_DIR/manager.pending"
  green "项目脚本与数据结构已更新。关联快照：$bundle；v2ray rollback.sh 将恢复该快照中的数据和服务状态。"
)

rollback_manager() (
  set -Eeuo pipefail
  local previous bundle='' armed=0 committed=0
  require_no_pending_manager
  previous=$(read_manager_pointer "$BACKUP_DIR/manager.rollback") || die '没有关联数据快照；拒绝仅恢复旧脚本。请保留当前数据并使用匹配版本。'
  bundle=$(mktemp -d "$BACKUP_DIR/manager-transaction.XXXXXX")
  trap 'finish_manager_transaction "$?" "$bundle" "$armed" "$committed"' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM
  capture_manager_bundle "$bundle"
  publish_manager_pointer "$BACKUP_DIR/manager.pending" "$bundle"
  armed=1
  restore_manager_bundle "$previous"
  publish_manager_pointer "$BACKUP_DIR/manager.rollback" "$bundle"
  committed=1
  rm -f -- "$BACKUP_DIR/manager.pending"
  green "已恢复关联的脚本与数据。回退前状态保留在 $bundle。"
)

uninstall_xray() {
  read -r -p "将停止服务并删除 Xray 程序与 /etc/xray 配置。继续？[y/N] " answer
  [[ ${answer,,} == y || ${answer,,} == yes ]] || return
  systemctl disable --now "$SERVICE_NAME" 2>/dev/null || true
  systemctl disable --now 'hysteria-v2ray-manager@*.service' 2>/dev/null || true
  rm -f "$SERVICE_FILE" "$XRAY_BIN" "$MANAGER_BIN" "$HYSTERIA_BIN" "$HYSTERIA_SERVICE_TEMPLATE"
  rm -rf "$CONFIG_DIR" "$ASSET_DIR" "$HYSTERIA_CONFIG_DIR"
  if [[ -e "$LEGACY_MANAGER_BACKUP" ]]; then
    install -m 755 "$LEGACY_MANAGER_BACKUP" "$MANAGER_BIN"
    green "已恢复安装前的 v2ray 管理命令。"
  fi
  systemctl daemon-reload
  green "已卸载本脚本创建的 Xray 程序与配置。xray 系统账户和 $BACKUP_DIR 中的备份已保留。"
}

runtime_menu() {
  local choice
  while :; do
    printf '\n'
    ui_box_title 'Xray 服务管理'
    ui_menu_item '1) 启动服务'
    ui_menu_item '2) 停止服务'
    ui_menu_item '3) 重启服务'
    ui_menu_item '4) 查看状态'
    ui_menu_item '5) 查看日志'
    ui_box_divider
    ui_menu_item '0) 返回主菜单'
    ui_box_bottom
    read -r -p '请选择 [0-5]:' choice
    case "$choice" in
      1) run_mutation service_action start; pause ;; 2) run_mutation service_action stop; pause ;; 3) run_mutation service_action restart; pause ;;
      4) show_status; pause ;; 5) show_logs; pause ;; 0) return ;; *) yellow "无效选择。"; pause ;;
    esac
  done
}

maintenance_menu() {
  local choice
  while :; do
    printf '\n'
    ui_box_title '维护与诊断'
    ui_menu_item '1) 更新 Xray Core'
    ui_menu_item '2) 一键更新项目脚本并迁移数据'
    ui_menu_item '3) 运行综合诊断'
    ui_menu_item '4) 检查并放行本机防火墙'
    ui_menu_item '5) 备份配置'
    ui_menu_item '6) 恢复最近备份'
    ui_menu_item '7) 轮换 REALITY 密钥'
    ui_menu_item '8) 恢复上一版管理脚本及关联数据（撤销快照后修改）'
    ui_menu_item '9) 路由、丢包与延迟测试'
    ui_menu_item '10) 查看项目信息'
    ui_box_divider
    ui_menu_item '0) 返回主菜单'
    ui_box_bottom
    read -r -p '请选择 [0-10]:' choice
    case "$choice" in
      1) run_mutation update_core; pause ;; 2) run_mutation update_manager; pause ;; 3) doctor || true; pause ;;
      4) run_mutation open_enabled_inbound_ports; pause ;; 5) run_mutation manual_backup; pause ;; 6) run_mutation restore_latest; pause ;;
      7) run_mutation rotate_reality_keys; pause ;; 8) run_mutation rollback_manager; pause ;; 9) route_test_menu ;;
      10) show_about; pause ;; 0) return ;; *) yellow "无效选择。"; pause ;;
    esac
  done
}
